trigger:
- master

pool:
  vmImage: 'windows-2019'
steps:
  - script: |
      git clone -b master https://github.com/flutter/flutter.git $BUILD_SOURCESDIRECTORY/../flutter
    displayName: 'Setup enviornment'
  - script: |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter packages get
    displayName: 'Install dependencies'
  - script:  |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter config --enable-windows-desktop
    displayName: 'Enable flutter desktop support'
  - script: 
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter build -v windows --debug
    displayName: 'Build'
