trigger:
- master

pool:
  vmImage: 'windows-2019'
steps:
  - script: |
      git clone -b master https://github.com/flutter/flutter.git $BUILD_SOURCESDIRECTORY/../flutter
      #set PATH=%PATH%;$BUILD_SOURCESDIRECTORY/../flutter/bin
      #set ENABLE_FLUTTER_DESKTOP=true
    displayName: 'Setup enviornment'
  - script: |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter packages get
    displayName: 'Install dependencies'
  - script: 
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter build -v linux --debug
    displayName: 'Build'
