trigger:
- master

pool:
  vmImage: 'windows-2019'
steps:
  - script: |
      git clone -b master https://github.com/flutter/flutter.git $BUILD_SOURCESDIRECTORY/../flutter
    displayName: 'Setup enviornment'
  - script: |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter packages get
    displayName: 'Install dependencies'
  - script:  |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter config --enable-web
    displayName: 'Enable web support'
  - script:  |
      $BUILD_SOURCESDIRECTORY/../flutter/bin/flutter build web
    displayName: 'Build'
  - task: GitHubPagesPublish@1
    inputs:
      docPath: "$(BUILD_SOURCESDIRECTORY)\\build\\web\\*"
      branchname: 'gh-pages'
      githubaccesstoken: $(github_pat)
      githubusername: 'GuruDhanush'
      repositoryname: 'flutter-winui'
      githubemail: $(github_email)
      commitmessage: 'Automated release $(Build.BuildNumber)'
